[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/shima/printer_data/comms/klippy.sock

[authorization]
trusted_clients:
    10.0.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    192.168.0.0/16
    FC00::/7
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[spoolman]
server: http://10.0.0.5:7912/
sync_rate: 5

[octoprint_compat]

[history]

[update_manager]
channel: dev
refresh_interval: 168

[timelapse]
##   Directory where the generated video will be saved
output_path: /mnt/printer/Printer_rec/Trident300/
##   Directory where ffmpeg is installed
ffmpeg_binary_path: /usr/bin/ffmpeg
# flip_x: True
# flip_y: True

[update_manager mainsail-config]
managed_services: klipper
origin: https://github.com/mainsail-crew/mainsail-config.git
path: /home/shima/mainsail-config
primary_branch: master
type: git_repo

## Klippain Shake&Tune automatic update management
[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: /home/shima/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper
 
[update_manager chopper-resonance-tuner]
type: git_repo
path: /home/shima/chopper-resonance-tuner
origin: https://github.com/MRX8024/chopper-resonance-tuner.git
primary_branch: main
managed_services: klipper

[update_manager KlipperScreen]
install_script: /home/shima/KlipperScreen/scripts/KlipperScreen-install.sh
requirements: /home/shima/KlipperScreen/scripts/KlipperScreen-requirements.txt
env: /home/shima/.KlipperScreen-env/bin/python
managed_services: KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
path: /home/shima/KlipperScreen
type: git_repo

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
managed_services: crowsnest
install_script: tools/pkglist.sh

[update_manager fluidd]
path: /home/shima/fluidd
repo: fluidd-core/fluidd
channel: stable
type: web
persistent_files:
    config.json
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main

[update_manager cartographer_plugin]
type: python
channel: stable
virtualenv: ~/klippy-env
project_name: cartographer3d-plugin
is_system_service: False
managed_services: klipper
info_tags: desc=Cartographer Plugin
## Crydteam TMC Flow Test automatic update management
[update_manager Crydteam-Tuning-Plugins]
type: git_repo
primary_branch: main
path: /home/shima/klipper_max_flow_test
origin: https://github.com/Fragmon/klipper_max_flow_test.git
managed_services: klipper
